---
title: "로또 당첨번호 통계 분석 (1 ~ 1124 회차)"
author: "Choi Sungmin"
format: html
editor: visual
---

```{r}
#| label: load
#| include: false

library(DBI)
library(RSQLite)
library(ggplot2)
library(dplyr)

db <- dbConnect(SQLite(), dbname = "lottery_results.sqlite")

cal_df <- function(results) {
  numbers <- unlist(results)
  number_freq <- table(numbers)
   
  number_freq_df <- as.data.frame(number_freq)
  colnames(number_freq_df) <- c("number", "frequency")
  
  number_freq_df <- number_freq_df %>%
    mutate(number = as.factor(number)) %>%
    arrange(as.numeric(as.character(number)))
  
  return(number_freq_df)
}

draw_graph <- function(number_freq_df, title, subtitle) {
  ggplot(number_freq_df, aes(x=number, y=frequency)) +
  geom_bar(stat="identity", fill="dodgerblue",position="dodge", width=0.8) +
  geom_text(aes(label=frequency), vjust=-0.3, color="black", size=3.5, position=position_dodge(width = 0.8)) +
  labs(title=title,
       subtitle=subtitle,
       x="Number", y="Frequency") +
  theme_minimal(base_size = 15) +
  theme(
    plot.title = element_text(hjust=0.5, face="bold"),
    plot.subtitle = element_text(hjust=0.5),
    axis.text.x = element_text(angle=45, hjust=0.5, size=8),
    panel.grid.major = element_line(color = "gray80"),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white", color = "gray90"),
    plot.background = element_rect(fill = "white", color = "gray90")
  )
}
```

```{r}
#| label: numbers-analysis
#| echo: false

results <- dbGetQuery(db, "SELECT number1, number2, number3, number4, number5, number6 FROM results")

number_freq_df <- cal_df(results)
draw_graph(number_freq_df, "Lotto Main Number Frequency", "보너스 번호를 제외한 번호의 통계 그래프입니다.")
```

```{r}
#| label: bonus-analysis
#| echo: false

results <- dbGetQuery(db, "SELECT bonus FROM results")

number_freq_df <- cal_df(results)
draw_graph(number_freq_df, "Lotto bonus Number Frequency", "보너스 번호만의 통계 그래프입니다.")
```

```{r}
#| label: all-analysis
#| echo: false

results <- dbGetQuery(db, "SELECT number1, number2, number3, number4, number5, number6, bonus FROM results")

number_freq_df <- cal_df(results)
draw_graph(number_freq_df, "Lotto ALL Number Frequency", "보너스 번호를 포함한 전체 번호의 통계 그래프입니다.")
```

```{r}
#| label: db-close
#| include: false

dbDisconnect(db)
```
